global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "main-module"
    static_configs:
      - targets: ["main-module-1:8000", "main-module-2:8000"]
    metrics_path: /metrics

  - job_name: "regex-module"
    static_configs:
      - targets: ["regex-module-1:8000", "regex-module-2:8000"]
    metrics_path: /metrics

  - job_name: "llm-service"
    static_configs:
      - targets: ["llm-service-1:8000", "llm-service-2:8000"]
    metrics_path: /metrics

  - job_name: "gliner-famous"
    static_configs:
      - targets: ["gliner-famous-1:8000", "gliner-famous-2:8000"]
    metrics_path: /metrics

  - job_name: "ml-for-all-types"
    static_configs:
      - targets: ["ml-for-all-types-1:8000", "ml-for-all-types-2:8000"]
    metrics_path: /metrics

  - job_name: "load-balancer"
    static_configs:
      - targets: ["load-balancer-exporter:9113"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]